### ISSUE TITLE
Got error 'PHP message: PHP Fatal error:  Call to a member function getTelephone() on boolean in app/code/community/Pagantis/Pagantis/Model/Webservice/Requestloan.php on line 245

### ISSUE THREAD

**Issue by droolo** [pagantis/pagamastarde-magento#4]
Por alguna razón que aún estoy analizando, algunos de los clientes registrados en Magento no tienen asignada una dirección de facturación por defecto, por lo que al llegar a la línea 245 del fichero app/code/community/Pagantis/Pagantis/Model/Webservice/Requestloan.php se produce un Fatal error (Call to a member function getTelephone() on boolean). Esat es la línea:
$this->_userData['phone'] = $customer->getPrimaryBillingAddress()->getTelephone();

Creo que sería interesante comprobar previamente si existe la "PrimaryBillingAddress"

**Comment by fatsifont2** [comment]
Vamos a aplicar la validación.
